/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(a){if(a.__qc)return a.__qc;var l=a.document,x=a.navigator,J="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),K=!1,f=0,c=[],y=[],s=[],L={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,
"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,d9vfr8QTWnv1E:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,
"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1},p=[],v={},D=0,E=[],z=null,W={},w={},ha=null,t,X=[].slice,ia,Y,M,k,A,Z,N,ja,ka,la,F,$,O,P,ma,G,na,oa,pa,qa,q,ra,B,Q,sa,aa,ta,ua,ba,r,va,ca,R,S,wa,xa,T,ya,da,ea,za,fa,C,H,I,U,ga,u=function(b){try{return{init:P,hash:O,rules:wa,hasRules:T,defaults:za,__qc:function(){return!0}}[b].apply(null,X.call(arguments,1))}catch(d){return!1}};u.evts=0;u.v=2;u.SD=J;u.qpixelsent=[];S=function(b){var d=b?b.length||
0:0,a;for(a=0;a<d;a++)if(!b[a])return!1;return!0};ea=function(b){(b=b||a._qacct)&&(ba(p,b)||p.push(b))};ba=function(b,d){var a=b.length,e;for(e=0;e<a;e++)if(b[e]===d)return!0;return!1};ca=function(b){return{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};R=function(b){var d,a;d=ca(b);if("array"===d)return b.slice(0);if("object"===d){d={};for(a in b)b.hasOwnProperty(a)&&(d[a]=b[a]);return d}return"string"===d?""+b:b};T=function(b){return ba(s,b)};za=function(b,d){var a;b&&((a=W[b])&&(d=
U(d,a)),d.qacct&&delete d.qacct,W[b]=d)};fa=function(b){var d,g;if(k(b))for(d in b)if("string"==typeof b[d]){d=b.event||"load";g=b.media||"webpage";"rule"!==d&&"load"!==d||"webpage"!==g&&"ad"!==g?q(b):(g=b.qacct||a._qacct,b.qacct=g,d=(d=w[g])?U(d,b):b,w[g]=d);ea(b.qacct);break}else"object"==typeof b[d]&&null!=b[d]&&fa(b[d])};U=function(b,d){var a={};a.qacct=b.qacct||d.qacct;a.event="load"===b.event||"load"===d.event?"load":b.event&&d.event?b.event||d.event:null;a.media=null;a.media="webpage"===b.media||
"webpage"===d.media?"webpage":"ad"===b.media||"ad"===d.media?"ad":b.media||d.media;aa(a,b,d);aa(a,d,b);a.event||delete a.event;a.media||delete a.media;return a};aa=function(b,d,a){var e,V,f,c,k,m;for(e in d)d.hasOwnProperty(e)&&!b.hasOwnProperty(e)&&(V=d[e],f=a[e],c="",k=!!V&&"string"==typeof V,m=!!f&&"string"==typeof f,k&&(c=V),k&&m&&(c+=","),m&&(c+=f),b[e]=c)};C=function(){var b=[],d,a;if(!(0<D)){va();for(d in w)w.hasOwnProperty(d)&&w[d]&&(a=w[d],b.push(a),delete w[d]);1==b.length&&q(b[0]);1<b.length&&
q(b)}};H=function(b){var d=[],a,e;for(a=0;a<b.length;a++)e=b[a],L.hasOwnProperty(e.substring(2))?v[e]=5:T(e)||d.push(e);if(0===d.length)C();else for(a=0;a<d.length;a++)e=d[a],s.push(e),ta(e)};ua=function(){for(var b;E[0]&&("loaded"==E[0].readyState||"complete"==E[0].readyState);)b=E.shift(),b.onreadystatechange=null,z.parentNode.insertBefore(b,z),I()};ta=function(b){var a,g;a=("https:"===l.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+b+".js";z=z||l.scripts[0];D++;g=l.createElement("script");
"async"in g?(g.src=a,g.async=!1,g.onload=function(){v[b]=0;I()},g.onerror=function(){v[b]=1;I()},z.parentNode.insertBefore(g,z)):g.readyState?(v[b]=2,E.push(g),g.onreadystatechange=ua,g.src=a):(v[b]=4,I())};I=function(){D-=0<D?1:0;C()};wa=function(){var b=!0,a,g,e;if(arguments.length){e=function(a){b?fa(a):q(a,!0)};for(a=0;a<arguments.length;a++)g=X.call(arguments[a],0),g.splice(1,0,e),xa.apply(null,g);b=!1;K&&C()}};xa=function(b,a){var g=[],e=[],c=a||q,f,k,l,m,n;if((f=X.call(arguments,2))&&f.length){k=
f[0]||S;l=f[1];m=f[2];f=m.length;for(n=0;n<f;n++)g.push(!1),e.push(null);g={p:b,f:g,r:k,c:m,a:l,v:e};T(b)||s.push(b);y.push(g);ya(g,c)}};ya=function(b,a){var g=b?b.c?b.c.length:0:0,e;for(e=0;e<g;e++)(function(e){var g,f;try{g=b.c[e][0],f=b.c[e].slice(1),f.splice(0,0,function(g){b.f[e]=!0;b.v[e]=g;da(b,a)}),g.apply(null,f)}catch(c){b.f[e]=!0,b.v[e]=!1,da(b,a)}})(e)};da=function(b,a){var g=b.a,e=b.v,f=b.r||S,c,k,l,m,n,h;(c=S(b.f))&&(c=c&&f(e));if(c)for(e=0;e<g.length;e++)try{k=g[e][0];l=1<g[e].length?
g[e].slice(1):[];l=l.concat(b.v);m=k.apply(null,l);n={qacct:b.p,event:"rule"};for(h in m)m.hasOwnProperty(h)&&"qacct"!==h&&(n[h]=m[h]);a(n)}catch(y){}};ia=function(){return Y(0)!==Y(6)?1:0};Y=function(b){b=new Date(2E3,b,1,0,0,0,0);var a=b.toGMTString(),a=new Date(a.substring(0,a.lastIndexOf(" ")-1));return b-a};M=function(b){return b.replace(/\./g,"%2E").replace(/,/g,"%2C")};A="function"===typeof encodeURIComponent?encodeURIComponent:M;k=function(b){return"undefined"!=typeof b&&null!=b};Z=function(){return Math.round(2147483647*
Math.random())};N=function(b){var a="",g=l.cookie,e;if(!g)return a;e=g.indexOf(b+"\x3d");b=e+b.length+1;-1<e&&(a=g.indexOf(";",b),0>a&&(a=g.length),a=g.substring(b,a));return a};ja=function(){var b="",a=F(),g,e,c;if(1===f)return";fpan\x3du;fpa\x3d";g=O(a);for(e=0;e<J.length;e++)if(J[e]===g)return";fpan\x3du;fpa\x3d";g=new Date;e=N("__qca");if(0<e.length){try{c=+e.split("-")[2],338688E5<g-c&&(l.cookie=["__qca\x3d",e,"; expires\x3d",(new Date(c+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",a].join(""))}catch(k){}b+=
";fpan\x3d0;fpa\x3d"+e}0===N("__qca").length&&(e="P0-"+Z()+"-"+g.getTime(),l.cookie=["__qca\x3d",e,"; expires\x3d",(new Date(g.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",a].join(""),e=N("__qca"),b=0<e.length?b+(";fpan\x3d1;fpa\x3d"+e):b+";fpan\x3du;fpa\x3d");return b};ka=function(b){l.cookie=b+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+F()};F=function(){var b,a,g,e;b=l.domain;"www."===b.substring(0,4)&&(b=b.substring(4,b.length));a=b.split(".");e=a.length;
if(3>e)return b;g=a[e-1];return 3>g.length?b:b=a[e-2]+"."+g};$=function(b,a){var g;for(g=0;g<a.length;g++)b^=a.charCodeAt(g),b+=(b<<1)+(b<<4)+(b<<7)+(b<<8)+(b<<24);return b};O=function(b){var a;a=$(2166136261,b);b=$(3386659096,b);return Math.round(Math.abs(a*b)/65536).toString(16)};Q=function(b,d,g){var e="",c=a._qacct,l=null,y="webpage",s="load",m={},n,h,c=d?d.qacct||a._qacct:a._qacct;n=w[c];d?n&&(d=U(d,n)):d=n;c&&delete w[c];if(null!=d)for(h in d)m[h]=!0,d.hasOwnProperty(h)&&"string"===typeof h&&
"string"===typeof d[h]&&("uid"===h||"uh"===h?(ma()||(l=O(d[h])),delete d[h]):"qacct"!==h&&(0<d[h].length?e+=";"+h+b+"\x3d"+A(d[h]):m[h]=!1,"media"===h&&(y=d[h]),"event"===h&&(s=d[h])));if("string"!==typeof c){if(!k(a._qacct)||0===a._qacct.length)return"";c=a._qacct}if(c&&(n=W[c]))for(h in n)"string"===typeof h&&n.hasOwnProperty(h)&&!m[h]&&(e+=";"+h+b+"\x3d"+A(n[h]),"media"===h&&(y=n[h]),"event"===h&&(s=n[h]));m=v[c];k(m)||(m=3);e+=";rf"+b+"\x3d"+m;"string"===typeof l&&(d.uh=l,e+=";uh"+b+"\x3d"+A(l));
if("webpage"===y&&"load"===s){for(d=0;d<u.qpixelsent.length;d++)if(u.qpixelsent[d]===c&&!g)return"";u.qpixelsent.push(c)}"ad"===y&&(f=1);return";a"+b+"\x3d"+c+e};sa=function(){var b=l.getElementsByTagName("meta"),a="",g,e,c,f;for(g=0;g<b.length;g++){c=b[g];if(1E3<=a.length)return a;k(c)&&k(c.attributes)&&k(c.attributes.property)&&k(c.attributes.property.value)&&k(c.content)&&(e=c.attributes.property.value,c=c.content,3<e.length&&"og:"===e.substring(0,3)&&(0<a.length&&(a+=","),f=80<c.length?80:c.length,
a+=M(e.substring(3,e.length))+"."+M(c.substring(0,f))))}return A(a)};la=function(b){return"object"===typeof b?["p","approved"===b.consent?"a":"d","asserted"===b.source?"e":"i"].join(""):""};ma=function(){var b=!1;k(a.external)&&(b=a.external,b="function"===typeof b.InPrivateFilteringEnabled&&!0===b.InPrivateFilteringEnabled());return b||"1"==x.doNotTrack||"yes"===x.doNotTrack||"1"==x.msDoNotTrack};q=function(b,d){var g="function"===typeof encodeURIComponent?"n":"s",e=Z(),y="",s="",p="",L="",m="",
n="u",h="1",r=0,t=[],q,v,w,z;f=0;k(u.qpixelsent)||(u.qpixelsent=[]);if(k(b))for(q in b)if("string"==typeof b[q]){s=Q("",b,d);break}else"object"==typeof b[q]&&null!=b[q]&&(++r,s+=Q("."+r,b[q],d));else"string"===typeof _qacct&&(s=Q("",null,d));0!==s.length&&(r=x.cookieEnabled?"1":"0","undefined"!=typeof x.javaEnabled&&(n=x.javaEnabled()?"1":"0"),k(a._qmeta)&&(p=";m\x3d"+A(a._qmeta),a._qmeta=null),self.screen&&(y=screen.width+"x"+screen.height+"x"+screen.colorDepth),v=new Date,w=ia(),z=ja(),a.location&&
a.location.href&&(L=A(a.location.href)),l&&l.referrer&&(m=A(l.referrer)),a.self===a.top&&(h="0"),q=sa(),t.push("/pixel;r\x3d"+e+s+z+";ns\x3d"+h+";ce\x3d"+r),t.push(";je\x3d"+n+";sr\x3d"+y+";enc\x3d"+g+";dst\x3d"+w+";et\x3d"+v.getTime()+";tzo\x3d"+v.getTimezoneOffset()+p+";ref\x3d"+m+";url\x3d"+L+";ogl\x3d"+q),c.push(t),B())};ra=function(b){var d=new Image;b=[a.location.protocol,"//pixel.",na(t)?"quantserve.com":"quantcount.com",b[0],";cm\x3d",la(t),b[1]].join("");d.alt="";d.src=b;d.onload=function(){d&&
"number"==typeof d.width&&3===d.width&&ka("__qca")}};B=function(){if(t)for(;c.length;)ra(c.shift());else qa()};na=function(b){return!0===b||1===b||1===b||k(b)&&"approved"===b.consent?!0:!1};qa=function(){if(!k(t)){if(a.top===a.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){oa("getConsent","advertising");return}}else if(a.postMessage&&"object"===typeof JSON){pa("getConsent","advertising");return}t=1}B()};oa=function(b,a){t=PrivacyManagerAPI.callApi(b,"quantserve.com",
F(),"truste.com",a);B()};pa=function(b,d){var c={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:b,self:"quantserve.com",domain:F(),authority:"truste.com",type:d}};if(a.addEventListener)a.addEventListener("message",G,!1);else if(a.attachEvent)a.attachEvent("onmessage",G);else{t=!0;B();return}try{a.top.postMessage(JSON.stringify(c),"*")}catch(e){}ha=setTimeout(function(){k(t)||(t=!0,B())},25)};G=function(b){var d=null;if(b.source===window.top){try{d="object"===typeof JSON&&JSON.parse(b.data)}catch(c){}d&&
"object"===typeof d.PrivacyManagerAPI&&(clearTimeout(ha),a.removeEventListener?window.removeEventListener("message",G,!1):a.detachEvent&&window.detachEvent("onmessage",G),t=d.PrivacyManagerAPI,B())}};ga=function(){var a=arguments,d,c;r([].slice.call(a));for(c=0;c<a.length;c++)d=a[c],q(d);p.length?H(p.slice(0)):C()};r=function(b){var d=ca(b);if("array"===d)for(d=0;d<b.length;d++)r(b[d]);else"object"===d&&ea(b.qacct||a._qacct)};va=function(){var b;a._qevents.length||a.ezt.length||"undefined"===typeof _qacct||
q({qacct:a._qacct});if(!u.evts){for(b in a._qevents)a._qevents.hasOwnProperty(b)&&q(a._qevents[b]);for(b in a.ezt)a.ezt.hasOwnProperty(b)&&q(a.ezt[b]);a._qevents={push:ga};a.ezt.push=function(){var b=arguments,c;if(k(a.queueManager))for(c=0;c<b.length;c++)a.queueManager.push(b[c]);else ga.apply(this,arguments)};u.evts=1}};P=function(){var b;k(a._qevents)||(a._qevents=[]);k(a.ezt)||(a.ezt=[]);a._qoptions&&(b=R(a._qoptions),r(a._qoptions),a._qevents.push(b),a._qoptions=null);a.qcdata&&(b=R(a.qcdata),
r(a.qcdata),a._qevents.push(b),a.qcdata=null);a.smarttagdata&&(b=R(a.smarttagdata),r(a.smarttagdata),a._qevents.push(b),a.smarttagdata=null);u.evts||(a._qevents.push=function(){r([].slice.call(arguments));H(p.slice(0));return[].push.apply(a._qevents,arguments)},a.ezt.push=function(){r([].slice.call(arguments));H(p.slice(0));return[].push.apply(a.ezt,arguments)});r(a.ezt);r(a._qevents);r({qacct:a._qacct});a._qoptions=null;p.length?H(p.slice(0)):C();K=!0};a.quantserve=a.quantserve||P;u.quantserve=P;
return u}(window);
try{__qc("hasRules","p-cwvCzSTmCGg_x")||function(a,l,x){try{__qc("defaults",a,{labels:"_fp.event.Default"})}catch(J){}var K=function(a,c,f){return a?"nc"===a?!c||!f||0>c.indexOf(f):"eq"===a?c===f:"sw"===a?0===c.indexOf(f):"ew"===a?(a=c.length-f.length,c=c.lastIndexOf(f,a),-1!==c&&c===a):"c"===a?0<=c.indexOf(f):!1:!1},f=function(a,c,f){var p;if(l.top===l.self)p=x.location.href;else{p=x.referrer;var v=x.createElement("a");v.href=p;p=v.href}K(c,p,f)?a(p):a(!1)},c=function(a){return"array"==={}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?
{labels:a.join(",")}:{labels:""+a}};__qc("rules",[a,null,[[c,"_fp.event.Homepage"]],[[f,"eq","https://www.tableau.com/"]]],[a,null,[[c,"_fp.event.Products"]],[[f,"ew","/products"]]],[a,null,[[c,"_fp.event.Products.Tableau Online"]],[[f,"ew","/products/cloud-bi"]]],[a,null,[[c,"_fp.event.Products.Tableau Server"]],[[f,"ew","/products/server"]]],[a,null,[[c,"_fp.event.Products.Tableau Desktop"]],[[f,"ew","/products/desktop"]]],[a,null,[[c,"_fp.event.Products.Tableau Mobile"]],[[f,"ew","/products/mobile"]]],
[a,null,[[c,"_fp.event.Products.Tableau Public"]],[[f,"ew","/s/"]]],[a,null,[[c,"_fp.event.Products.Tableau Embedded Analytics"]],[[f,"ew","/embedded-analytics"]]],[a,null,[[c,"_fp.event.Stories"]],[[f,"ew","/stories"]]],[a,null,[[c,"_fp.event.Stories.Industries"]],[[f,"ew","stories?topic\x3dindustries"]]],[a,null,[[c,"_fp.event.Stories.Activities"]],[[f,"ew","stories?topic\x3dactivities"]]],[a,null,[[c,"_fp.event.Stories.Technology"]],[[f,"ew","stories?topic\x3dtechnology"]]],[a,null,[[c,"_fp.event.Stories"]],
[[f,"c","/stories"]]],[a,null,[[c,"_fp.event.Stories.Solutions"]],[[f,"ew","solutions"]]],[a,null,[[c,"_fp.event.Stories.Viz Gallery"]],[[f,"c","/stories/gallery"]]],[a,null,[[c,"_fp.event.Stories.Enterprise"]],[[f,"ew","/enterprise"]]],[a,null,[[c,"_fp.event.Learning"]],[[f,"ew","/learn"]]],[a,null,[[c,"_fp.event.Learning.Free Training Videos"]],[[f,"ew","/learn/training"]]],[a,null,[[c,"_fp.event.Learning.Live Online Training"]],[[f,"ew","/learn/live-training"]]],[a,null,[[c,"_fp.event.Learning.Classroom Training"]],
[[f,"ew","/learn/classroom"]]],[a,null,[[c,"_fp.event.Learning.Product Demos"]],[[f,"ew","/learn/demos"]]],[a,null,[[c,"_fp.event.Learning.Video Tutorials"]],[[f,"ew","/tutorials/"]]],[a,null,[[c,"_fp.event.Learning.Live Online Training"]],[[f,"c","/learn/training/live/"]]],[a,null,[[c,"_fp.event.Learning.Classroom Training"]],[[f,"c","/learn/classroom/"]]],[a,null,[[c,"_fp.event.Learning.Whitepapers"]],[[f,"c","/learn/whitepapers"]]],[a,null,[[c,"_fp.event.Learning.Webinars"]],[[f,"c","/learn/webinars"]]],
[a,null,[[c,"_fp.event.Learning.Product Demos"]],[[f,"c","/learn/training/live/"]]],[a,null,[[c,"_fp.event.Community"]],[[f,"ew","/community"]]],[a,null,[[c,"_fp.event.Partners"]],[[f,"c","/partners"]]],[a,null,[[c,"_fp.event.Community.Events"]],[[f,"c","/community/events"]]],[a,null,[[c,"_fp.event.Blog"]],[[f,"c","/blog/"]]],[a,null,[[c,"_fp.event.Support"]],[[f,"ew","/support"]]],[a,null,[[c,"_fp.event.Support.Desktop"]],[[f,"c","/support/desktop"]]],[a,null,[[c,"_fp.event.Support.Server"]],[[f,
"c","/support/server"]]],[a,null,[[c,"_fp.event.Support.Online"]],[[f,"c","/support/online"]]],[a,null,[[c,"_fp.event.Support.Consulting"]],[[f,"c","/support/consulting"]]],[a,null,[[c,"_fp.event.Support.Knowledgebase"]],[[f,"c","/support/knowledgebase"]]],[a,null,[[c,"_fp.event.Articles"]],[[f,"c","/articles/"]]],[a,null,[[c,"_fp.event.About"]],[[f,"ew","/about"]]],[a,null,[[c,"_fp.event.About.Mission"]],[[f,"c","/about/mission"]]],[a,null,[[c,"_fp.event.About.Leadership"]],[[f,"c","/about/leadership"]]],
[a,null,[[c,"_fp.event.About.Newsroom"]],[[f,"c","/about/newsroom"]]],[a,null,[[c,"_fp.event.Free Trial - Overview Page"]],[[f,"ew","/products/trial"]]],[a,null,[[c,"_fp.event.Contact Us Confirmation"]],[[f,"c","/contact?signin"]]],[a,null,[[c,"_fp.event.Contact Us"]],[[f,"c","/about/contact"],[f,"nc","?signin"]]])}("p-cwvCzSTmCGg_x",window,document)}catch(nfe$$4){}quantserve();try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$5){};